LIME-102: Fixed log in
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #112
Opened 2024-02-19 20:39 UTC by SergiiTernytskyi

Fixed log in

2024-02-20 08:48 UTC, SergiiTernytskyi commented
![login](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/43b5a118-ce88-4d4f-939b-f47fe566890a)
![signin](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/a51d48e8-f633-406d-bdb2-33e804621ea3)

2024-02-20 12:14 UTC, nikita-remeslov requested changes
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/2b8d16de-1a7e-4513-bd1f-3a60b270ab74)
It looks like we need to update the style to fit the design
Also, I don't understand why in one place we have social buttons, but in another, we don't have

2024-02-20 15:08 UTC, SergiiTernytskyi commented
![login-2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/5986fc56-5cbb-48f4-8823-60448424c2d1)
![signup-2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/bed2df03-ba52-4b0f-9520-92eb5bb8aba2)

2024-02-21 07:57 UTC, anton-otroshchenko commented on backend/src/common/database/base-database.package.ts
> +            this.appConfig.ENV.APP.ENVIRONMENT === AppEnvironment.DEVELOPMENT
why did you change this?

2024-02-21 08:08 UTC, SergiiTernytskyi commented on backend/src/common/database/base-database.package.ts
> +            this.appConfig.ENV.APP.ENVIRONMENT === AppEnvironment.DEVELOPMENT
Sorry I forgot to change it back

2024-02-21 08:35 UTC, dimapopovych approved these changes

2024-02-21 15:48 UTC, nikita-remeslov approved these changes

2024-02-21 15:48 UTC, merged