LIME-33: + refresh user
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #113
Opened 2024-02-19 22:18 UTC by ivanbilobrov07

2024-02-20 17:20 UTC, stpalamar commented on frontend/src/bundles/auth/store/slice.ts
> +    isRefreshing: false,
Why we need isRefreshing when we have dataStatus already?

2024-02-20 18:29 UTC, dimapopovych requested changes

2024-02-20 18:29 UTC, dimapopovych commented on backend/src/bundles/users/user.controller.ts
> +                        user: UserGetCurrentRequestDto;
Let's retrieve the user from the database in the plugin and decorate the request with the UserEntity. Here simply take the user from the options and return it. Additionally, let's add Swagger documentation.

2024-02-20 21:38 UTC, ivanbilobrov07 commented on frontend/src/bundles/auth/store/slice.ts
> +    isRefreshing: false,
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/eafadbd8-d3ee-4e76-8e11-53cc0930f810

Then, we will have the functionality like here, when we have loader on the page when trying to sign in and it is a little but weird that the whole page disapear

2024-02-21 20:51 UTC, dimapopovych requested changes

2024-02-21 20:51 UTC, dimapopovych commented on backend/src/common/plugins/auth-plugin.ts
> +                    const user = await userService.find({ id: userId });
check if user is present, otherwise throw error

2024-02-21 20:51 UTC, dimapopovych commented on shared/src/bundles/users/types/user-get-current-request-dto.type.ts
> +type UserGetCurrentRequestDto = {
you don't need this dto anymore

2024-02-21 20:51 UTC, dimapopovych commented on backend/src/bundles/users/user.controller.ts
> +                        user: UserGetCurrentRequestDto;
here should be UserAuthResponseDto, also change type in declaration file.
add swagger

2024-02-21 21:32 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/auth/store/slice.ts
> +    isRefreshing: false,
have you merged the development branch? loader is displayed inside the button now

2024-02-21 21:33 UTC, SofiiaTrokhymchuk commented
You seem to have outdated types and auth flow. Please, merge the development branch

2024-02-21 23:02 UTC, ivanbilobrov07 commented on frontend/src/bundles/auth/store/slice.ts
> +    isRefreshing: false,
Yes, I just provided a video, how it would be if I use dataStatus for Loader while refreshing

2024-02-22 13:30 UTC, dimapopovych requested changes
change fastify-types.d.ts, also seems like user is not passed to options for handler or am I missing something

2024-02-22 13:30 UTC, dimapopovych commented on backend/src/bundles/users/user.controller.ts
> +     *       bearerFormat: JWT
lets move this to swaggerJsdoc fn in BaseServerApplication api like this
```
definition: {
  components: {
    securitySchemes: {
	  bearerAuth: {
        bearerFormat: "JWT",
		scheme: "bearer",
		type: "http",
     },
  },
},
```

2024-02-22 13:30 UTC, dimapopovych commented on backend/src/bundles/users/user.controller.ts
> +     *       bearerFormat: JWT
also remove declaration in /users

2024-02-22 17:56 UTC, dimapopovych approved these changes

2024-02-22 18:21 UTC, valery-chumak approved these changes

2024-02-22 18:29 UTC, ArtemLymarenko approved these changes

2024-02-22 19:29 UTC, SofiiaTrokhymchuk approved these changes

2024-02-23 10:59 UTC, merged