LIME-134: * Removed state dependency, added props for info..
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #135
Opened 2024-02-21 13:54 UTC by DavidCharif

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/642419eb-293a-41bd-bbda-f517f67540ae)

2024-02-21 13:56 UTC, dimapopovych requested changes

2024-02-21 13:56 UTC, dimapopovych commented on frontend/src/bundles/common/components/avatar/avatar.tsx
> +    avatarUrl: string;
```suggestion
    avatarUrl: string | null;
```

2024-02-21 14:03 UTC, DavidCharif commented on frontend/src/bundles/common/components/avatar/avatar.tsx
> +    avatarUrl: string;
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/2cd9c5a1-483c-42c4-88a8-f4da82eb9ef4)

2024-02-21 18:43 UTC, jhladkov approved these changes

2024-02-21 22:42 UTC, dimapopovych approved these changes

2024-02-22 11:58 UTC, nikita-remeslov approved these changes

2024-02-22 11:58 UTC, merged