LIME-139: Create notifications component.
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #160
Opened 2024-02-23 02:15 UTC by DavidCharif

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/acf1f156-9bd9-4bd0-bfa5-1992166d22ea)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/dd8bed2c-0358-48b1-861d-21d2c0c6f1c2)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/16f66f2a-d164-4393-8af8-48033ebbbbfa)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/156179ba-b239-4a52-8a5e-0e602b4f433a

2024-02-23 11:07 UTC, nikita-remeslov commented
Looks like it does not fit our design. we should update the colors

2024-02-27 08:30 UTC, DavidCharif commented
> Looks like it does not fit our design. we should update the colors



https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/1667fd27-1722-4038-a78e-a7c9470969ca

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/b60185d2-f5d4-49c8-8fd4-65c5c8bbcb34)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/d8d0d51e-7839-45b5-98a5-c05fee2cb49d)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/4e6b1ff3-e01f-46a9-840e-09156b1cf1b3)

2024-02-27 20:25 UTC, ArtemLymarenko commented
You can try to use popover component from common folder and not create all those divs with position relative/absolute.

2024-02-29 01:39 UTC, DavidCharif commented
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/904559d7-6ad8-4597-911a-7a8bb8dd7335

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/2b8c0041-57c5-4b2c-8378-d8494f6b2b0a)

2024-02-29 17:54 UTC, dimapopovych approved these changes, later dismissed

2024-03-02 10:13 UTC, dimapopovych requested changes

2024-03-02 10:13 UTC, dimapopovych commented on frontend/src/bundles/common/components/header/components/notifications/enums/notifications.enums.ts
> +type NotificacitionType = {
this is not enum, move to proper folder

2024-03-02 10:13 UTC, dimapopovych commented on frontend/src/bundles/common/components/header/components/notifications/notification-component.tsx
> +    const [notifications, setNotifications] = useState([
maybe we can move this state to the store and add necessary actions as well at this point?

2024-03-04 16:15 UTC, nikita-remeslov commented
many changes not related to you task

2024-03-05 11:37 UTC, nikita-remeslov requested changes
the same. you did not change strave in your ticket. You should fix the diff of your PR

2024-03-05 18:46 UTC, closed without merging