Task/lime 144 notification api
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #186
Opened 2024-02-26 21:47 UTC by ivanbilobrov07

2024-02-27 08:21 UTC, anton-otroshchenko requested changes

2024-02-27 08:21 UTC, anton-otroshchenko commented on backend/src/bundles/notifications/notification.controller.ts
> +            // payload: await this.notificationService.findAll(user.id)
do we need this comment?

2024-02-27 08:21 UTC, anton-otroshchenko commented on backend/src/bundles/notifications/notification.controller.ts
> +            // payload: await this.notificationService.dismiss(params.notificationId, user.id)
same here

2024-02-27 08:21 UTC, anton-otroshchenko commented on backend/src/bundles/notifications/notification.controller.ts
> +            // payload: await this.notificationService.delete({id: params.notificationId, userId: id})
and here

2024-02-27 08:21 UTC, anton-otroshchenko commented on backend/src/bundles/notifications/notification.repository.ts
> +            : false;
```suggestion
        return Boolean(await this.notificationModel
            .query()
            .where(query)
            .del()
            .execute())
```

will this work?

2024-02-27 19:50 UTC, ivanbilobrov07 commented on backend/src/bundles/notifications/notification.controller.ts
> +            // payload: await this.notificationService.findAll(user.id)
oh, sorry forgot about them

2024-02-27 19:55 UTC, ivanbilobrov07 commented on backend/src/bundles/notifications/notification.repository.ts
> +            : false;
yes, it is the same, but I can replace to your suggesion

2024-02-27 20:58 UTC, ArtemLymarenko commented on backend/src/bundles/notifications/notification.repository.ts
> +    }
I think it's better to use patchAndFetchById since you not updating all fields and change **query** parameter name to **payload**.

2024-02-27 20:58 UTC, ArtemLymarenko commented on backend/src/bundles/notifications/types/notification-type.type.ts
> +export { NotificationType };
Why did you create it in types when it's enum?

2024-02-28 08:39 UTC, dimapopovych requested changes

2024-02-28 08:39 UTC, dimapopovych commented on backend/src/bundles/notifications/notification.controller.ts
> +import { ApiPath, HttpCode } from 'shared';
imports

2024-02-28 08:39 UTC, dimapopovych commented on backend/src/bundles/notifications/notification.controller.ts
> +                        query: PaginationParameters;
add validation schema

2024-02-28 08:39 UTC, dimapopovych commented on backend/src/bundles/notifications/notification.repository.ts
> +    }): Promise<{ items: NotificationEntity[]; total: number }> {
can we add type helper for this?
something like 
type Paged<T> = { items: T, total: number }
Maybe you'll come up with a better name than that.

2024-02-28 08:39 UTC, dimapopovych commented on backend/src/bundles/notifications/notification.repository.ts
> +            .orderBy('updated_at', 'desc')
why are you using snake case here?

2024-02-28 08:39 UTC, dimapopovych commented on backend/src/migrations/20240227185115_add_notifications_table.ts
> +    IS_READ: 'isRead',
is_read

2024-02-28 08:39 UTC, dimapopovych commented on backend/src/migrations/20240227185115_add_notifications_table.ts
> +        table.string(ColumnName.TYPE).defaultTo(NotificationType.DEFAULT);
let's create enum for this

2024-03-01 11:58 UTC, nikita-remeslov submitted a review, later dismissed

2024-03-01 19:03 UTC, stpalamar commented on backend/src/bundles/notifications/notification.repository.ts
> +            .where('userId', userId);
you can use .count() to get the amount of all the rows instead of fetching them from the database. This will be faster when we have a large number of records in the database

2024-03-02 10:32 UTC, dimapopovych requested changes

2024-03-02 10:32 UTC, dimapopovych commented on backend/src/bundles/notifications/notification.repository.ts
> +            .patchAndFetchById(notificationId, payload)
you don't need patchAndFetch when you are using returning method, just patch + findById

2024-03-02 10:32 UTC, dimapopovych commented on backend/src/bundles/notifications/notification.repository.ts
> +            .offset((page - 1) * limit)
Objection has dedicated method page() for this, it will return page and total count.

2024-03-04 21:37 UTC, ivanbilobrov07 commented on backend/src/bundles/notifications/notification.repository.ts
> +            .where('userId', userId);
I have used  const total = await this.notificationModel.query().resultSize();

2024-03-05 11:32 UTC, nikita-remeslov submitted a review, later dismissed

2024-03-05 11:41 UTC, dimapopovych approved these changes, later dismissed

2024-03-06 21:09 UTC, dimapopovych approved these changes, later dismissed

2024-03-07 09:38 UTC, anton-otroshchenko approved these changes

2024-03-07 09:43 UTC, nikita-remeslov approved these changes

2024-03-07 09:43 UTC, merged