LIME-202: Add user info card
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #211
Opened 2024-02-27 17:59 UTC by SergiiTernytskyi

Added user info card

2024-02-27 17:59 UTC, SergiiTernytskyi commented
![user-info](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/f17346ed-1ab3-4eb1-8563-3c1d4bd8abae)

2024-02-28 07:57 UTC, anton-otroshchenko requested changes

2024-02-28 07:57 UTC, anton-otroshchenko commented on frontend/src/bundles/common/components/user-info-card/user-info-card.tsx
> +    achievements?: [];
Don't we have type for achievement?

2024-02-28 07:57 UTC, anton-otroshchenko commented on frontend/src/bundles/common/helpers/date-converter/date-converter.ts
add .helper to file name

2024-02-29 18:29 UTC, dimapopovych requested changes

2024-02-29 18:29 UTC, dimapopovych commented on frontend/src/bundles/common/helpers/date-converter/date-converter.ts
> +
rename to formatDate or something similar, function name should start with noun. Also we already have similar helper, maybe it's worth to create formatDate(date, format) where format will be value from enum or so.

2024-03-11 10:01 UTC, SergiiTernytskyi commented
![Screenshot_13](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/7d0df49f-416d-4be2-851f-6672b995f97e)

2024-03-11 20:19 UTC, dimapopovych requested changes

2024-03-11 20:19 UTC, dimapopovych commented on frontend/src/bundles/common/components/user-info-card/user-info-card.tsx
> +    const onViewAllClick = useCallback((): void => {
handlers should have handle prefix

2024-03-11 21:53 UTC, SergiiTernytskyi commented on frontend/src/bundles/common/components/user-info-card/user-info-card.tsx
> +    const onViewAllClick = useCallback((): void => {
Thats wright

2024-03-12 10:22 UTC, nikita-remeslov approved these changes

2024-03-12 10:22 UTC, merged