LIME-199:  Add chart for progress.
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #214
Opened 2024-02-28 03:22 UTC by DavidCharif

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/627d98c9-cbd8-4915-98fa-ab945e612dd4)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/dfe9e636-86f5-4c12-8f04-2f83ffca4387

2024-02-28 15:39 UTC, anton-otroshchenko requested changes

2024-02-28 15:39 UTC, anton-otroshchenko commented on frontend/src/bundles/overview/components/chart-goal-progress/chart-goal-progress.tsx
> +};
Change the name of the type

2024-02-28 15:39 UTC, anton-otroshchenko commented on frontend/src/bundles/overview/components/chart-goal-progress/chart-goal-progress.tsx
> +        if (newValue !== null) {
```suggestion
        if (newValue) {
```

2024-02-28 15:39 UTC, anton-otroshchenko commented on frontend/src/bundles/overview/components/chart-goal-progress/chart-goal-progress.tsx
> +                chartData={dataMapping[currentData.value] || weeklyData}
```suggestion
                chartData={dataMapping[currentData.value] ?? weeklyData}
```

2024-02-28 18:59 UTC, ArtemLymarenko commented on frontend/src/bundles/overview/components/chart-goal-progress/chart-goal-progress.tsx
I think it's better to create constant folder for all this data.

2024-02-28 18:59 UTC, ArtemLymarenko commented on frontend/src/bundles/overview/components/chart-goal-progress/chart-goal-progress.tsx
> +    });
```suggestion
    const [currentData, setCurrentData] = useState<SelectOption>(data[0]);
```

2024-02-28 18:59 UTC, ArtemLymarenko commented on frontend/src/bundles/overview/components/chart-goal-progress/chart-goal-progress.tsx
> +                    },
```suggestion
                    callback: (value: number): string => `${value}%`;,
```
Is it possible to do like this?

2024-02-28 21:42 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/f9a5df65-2d6a-4a21-af78-fa77908b6a44)

2024-02-29 18:32 UTC, dimapopovych submitted a review, later dismissed

2024-02-29 19:03 UTC, nikita-remeslov approved these changes

2024-02-29 19:04 UTC, nikita-remeslov requested changes

2024-02-29 19:04 UTC, nikita-remeslov commented on frontend/src/bundles/overview/components/charts/types/bar-chart-data.types.ts
1 type = 1 fiel

2024-03-01 15:08 UTC, anton-otroshchenko approved these changes

2024-03-04 16:12 UTC, nikita-remeslov approved these changes

2024-03-04 16:12 UTC, merged