LIME-219: * Theme switch general layout
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #265
Opened 2024-03-01 13:38 UTC by DavidCharif

2024-03-01 13:40 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/6d7ed225-b577-4142-af76-db0a1363de15)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/49dc004a-b103-4cda-8d51-30a82688bb26)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/d35edc58-0b15-4825-907d-0c1d03183afd)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/c264ba1d-722f-4bd1-8c4b-e1acef9fa649)

2024-03-01 14:37 UTC, DavidCharif commented
Testing
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/d62803bd-a318-4260-a3af-4ce98d9bc000

2024-03-01 21:30 UTC, valery-chumak approved these changes, later dismissed

2024-03-04 09:06 UTC, anton-otroshchenko requested changes

2024-03-04 09:06 UTC, anton-otroshchenko commented on frontend/src/bundles/common/components/theme-switcher/theme-switcher.tsx
> +function ThemeSwitcher({
```suggestion
function handleThemeSwitcher({
```

2024-03-04 09:06 UTC, anton-otroshchenko commented on frontend/src/bundles/common/components/theme-switcher/theme-switcher.tsx
> +function ThemeSwitcher({
A10 https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

2024-03-04 15:56 UTC, DavidCharif commented
Update testing
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/33d9c903-f901-4516-be02-827d7742fee5

2024-03-04 16:04 UTC, nikita-remeslov commented
Please double check all components
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/9857c7c0-4e14-4d24-b0fa-994ba4a5c4f6)

your version
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/6a9e8fc6-c766-4f09-86a4-5ce21b64f781)

2024-03-04 16:45 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/ffbfada1-3e42-42c9-85eb-f10cb73e1e7c)

2024-03-04 16:52 UTC, DavidCharif commented
Update
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/f37b001a-44d8-426e-95eb-9533f3d038bd

2024-03-04 17:19 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/79b5915c-bd01-4879-834d-68016909f543)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/efb8c34a-e929-4da1-8145-d2043d40ad01)

2024-03-04 17:40 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/1ca29828-3812-4101-9dfc-83a441c9145d)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/40272670-fb98-48d5-a0bb-7751386e51f0)

2024-03-04 20:41 UTC, valery-chumak approved these changes, later dismissed

2024-03-05 13:26 UTC, DavidCharif commented
Update: 
Before
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/b210a099-734c-4fb8-bda5-c3ec55349e91)

After
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/d9d74b63-2eb6-4c2f-a99f-547e8cb5b47f)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/b3607da1-45dd-4e8d-9c22-098117fc09c9)

2024-03-05 13:57 UTC, nikita-remeslov submitted a review, later dismissed

2024-03-05 14:11 UTC, valery-chumak commented
@DavidCharif 
The Logout button on light theme is not visible
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/338369c0-7e4f-4d61-8e63-8f1d23da42e7)

2024-03-05 14:13 UTC, valery-chumak commented
Could you also please change the colors for radio buttons in profile settings for light theme? Because it is not changing at all
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/089be6d7-42aa-4aca-8385-fce53e375ab5)

2024-03-05 14:27 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/c983aa55-04e9-4cec-bc97-6ff6d909f476)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/d9a13fb3-55f9-4065-a838-ba4fbee2e484)
Fix radio buttons and logout

2024-03-05 14:38 UTC, valery-chumak approved these changes, later dismissed

2024-03-05 16:00 UTC, DavidCharif commented
Before
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/c58a2aee-2eba-4633-a417-c564fe2cae46)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/b33d3108-adbb-41b7-b48b-73c8e3b7d8f6)

After
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/01a3831b-9c1c-4a81-bb98-ea4452159ac5)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/cf592931-85c5-4f7c-ba3a-909939d2ed28)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/5b599e2d-8e6e-4890-9ace-50d71e3b4880)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/0cd14161-970c-4579-acfb-6ba2c75c780a)

2024-03-06 19:41 UTC, stpalamar commented
Can you please make this text the same for the sign-up and sign-in forms?
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/f32e832f-a732-4129-a175-80c3c0ea2f08)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/414fb4a8-9db5-4136-871b-862e061f4eaf)

2024-03-06 19:47 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/7fcda9f2-8ab9-48ba-97cb-b6b51eec830f)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/67e13172-1dd3-4660-8786-6966ea15d377)

2024-03-06 19:50 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/919b90a2-621f-4344-b76b-ee2124540586)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/2ec29027-9dec-4920-8ae3-46a081248902)

2024-03-07 17:39 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/27aa2388-57cb-417f-99cf-a3691057574f)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/9bb7d411-8005-45ab-9f19-e26d9a1e92af)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/0b5c01a1-90b2-4591-92f0-4f082ff855ce)

2024-03-07 21:12 UTC, stpalamar submitted a review, later dismissed

2024-03-08 15:19 UTC, DavidCharif commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/399b9ba8-d295-478d-ab5b-21e4f59c6de0)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/edc4d0ca-03a3-4dca-a7a5-ab260901dd1c)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/0c02cb8a-dfc5-4825-99e7-4202a1b5efa7)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/2bf51b61-ac81-4243-824f-cf526206cef1)

2024-03-11 10:50 UTC, nikita-remeslov approved these changes

2024-03-11 10:50 UTC, merged