LIME-273: Fix Quality Criteria (Check 1)
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #278
Opened 2024-03-04 11:49 UTC by valery-chumak

2024-03-04 16:42 UTC, nikita-remeslov requested changes
Looks like you skip some files

2024-03-04 16:42 UTC, nikita-remeslov commented on backend/src/bundles/oauth/enums/rows-number.enum.ts
Looks like it should be constant

2024-03-04 16:42 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/theme-switcher/theme-switcher.tsx
> +                    checked={theme === Theme.DARK ? true : false}
```suggestion
                    checked={theme === Theme.DARK}
```

2024-03-04 21:40 UTC, dimapopovych requested changes

2024-03-04 21:40 UTC, dimapopovych commented on frontend/src/bundles/common/components/checkbox/checkbox.tsx
> +                        aria-label="Toggle Checkbox"
I don't think thats very valuable description. Could we pass as props screen-reader only label for checkboxes?

2024-03-04 21:40 UTC, dimapopovych commented on frontend/src/bundles/common/components/router-provider/router-provider.tsx
> +                            isAlreadyProtected ?? shouldProtect,
invalid, it will not work with nullish coalescing since first operand is boolean

2024-03-05 11:07 UTC, nikita-remeslov submitted a review, later dismissed

2024-03-05 11:10 UTC, anton-otroshchenko submitted a review, later dismissed

2024-03-05 11:12 UTC, dimapopovych commented on backend/src/bundles/subscriptions/constants/rows-number.constant.ts
> +const MINIMUM_DELETED_ROWS = 0;
can we move this to common constants instead of defining in every bundle?

2024-03-05 11:12 UTC, dimapopovych approved these changes, later dismissed

2024-03-05 11:28 UTC, nikita-remeslov approved these changes

2024-03-05 11:28 UTC, merged