LIME-143: Add workout page
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #280
Opened 2024-03-04 17:49 UTC by SofiiaTrokhymchuk

I need [workout api](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/181), so changes from there are also here

![big screen](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/b65e5d9d-2d42-4141-b90b-ba6d3652c897)
![small screen](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/a3edd0cc-2f8d-40a1-a945-11f4f11977b7)
![not found](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/7e013a09-9a57-45f4-a3c6-f4c091dcd446)

2024-03-05 08:18 UTC, dimapopovych commented
Could you change source branch to simplify diff?

2024-03-05 08:30 UTC, SofiiaTrokhymchuk commented
Done

2024-03-05 09:00 UTC, dimapopovych requested changes

2024-03-05 09:00 UTC, dimapopovych commented on frontend/src/bundles/common/helpers/get-time-from-date/get-time-from-date.helper.ts
> +};
since we already have date-fns
format(date, 'HH:mm')

2024-03-05 09:00 UTC, dimapopovych commented on frontend/src/bundles/workouts/pages/workout/workout.tsx
> +            navigate(`${AppRoute.WORKOUT}/${firstWorkoutId}`);
use AppRoute.WORKOUT_$ID and configureString helper

2024-03-05 09:14 UTC, anton-otroshchenko requested changes

2024-03-05 09:14 UTC, anton-otroshchenko commented on frontend/src/bundles/common/helpers/get-time-from-date/get-time-from-date.helper.ts
> +    const minutesString = minutes >= 10 ? String(minutes) : `0${minutes}`;
B31 https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

2024-03-06 16:19 UTC, nikita-remeslov approved these changes

2024-03-06 16:19 UTC, merged