LIME-288: Fix Connections page url
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #290
Opened 2024-03-05 10:17 UTC by valery-chumak

2024-03-05 10:22 UTC, valery-chumak commented
Could you please add a new milestone for this week? Because checks for PR are not passed because of it(

2024-03-05 11:40 UTC, anton-otroshchenko submitted a review, later dismissed

2024-03-05 12:03 UTC, nikita-remeslov requested changes

2024-03-05 12:03 UTC, nikita-remeslov commented on frontend/src/bundles/profile/components/profile-sub-nav/profile-sub-nav.tsx
we can use AppRoute here, for routes

2024-03-06 20:00 UTC, stpalamar approved these changes

2024-03-06 21:15 UTC, ArtemLymarenko approved these changes

2024-03-07 21:12 UTC, dimapopovych approved these changes

2024-03-08 08:17 UTC, nikita-remeslov approved these changes

2024-03-08 08:17 UTC, merged