LIME-293: Fix redirecting to auth page
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #297
Opened 2024-03-05 17:46 UTC by valery-chumak

2024-03-05 18:12 UTC, ivanbilobrov07 submitted a review, later dismissed

2024-03-06 12:47 UTC, anton-otroshchenko commented on frontend/src/bundles/auth/pages/auth.tsx
> +    if (isRefreshing || user) {
`|| user` - is it necessary?

2024-03-08 11:06 UTC, valery-chumak commented on frontend/src/bundles/auth/pages/auth.tsx
> +    if (isRefreshing || user) {
Yes, because without this condition it shows a sign-in page for a second after loader for authorized user

2024-03-08 11:10 UTC, valery-chumak commented
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/4e03ca33-df7a-450d-a50c-e6a5e3f798be

2024-03-11 10:47 UTC, nikita-remeslov approved these changes

2024-03-11 10:48 UTC, nikita-remeslov requested changes

2024-03-11 10:48 UTC, nikita-remeslov commented on frontend/src/bundles/auth/pages/auth.tsx
>      }));
```suggestion
    const { dataStatus, user, isRefreshing } = useAppSelector(({ auth }) => auth);
```

2024-03-11 16:20 UTC, valery-chumak commented on frontend/src/bundles/auth/pages/auth.tsx
>      }));
Fixed)

2024-03-11 20:30 UTC, dimapopovych approved these changes

2024-03-12 10:19 UTC, nikita-remeslov approved these changes

2024-03-12 10:19 UTC, merged