LIME-254: Add Landing Page
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #312
Opened 2024-03-06 14:03 UTC by stpalamar

1. Changed route flow. The overview route is the home page for authorized users. 
2. "Download buttons" on the landing page redirect to sign-up since we decided with QA 
3. "Learn more" button has anchor to How It Works section

**Demo**

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/15556c54-00d6-4c49-bc74-47a6b43b5124

**Route flow**

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/00da8d54-94ac-4ad4-bd8e-68e98c2c39aa

2024-03-06 14:07 UTC, DavidCharif submitted a review, later dismissed

2024-03-06 21:33 UTC, valery-chumak requested changes

2024-03-06 21:33 UTC, valery-chumak commented on frontend/src/bundles/landing/pages/landing.tsx
> +                        <img src={logo} alt="Logo" />
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/cad60997-ba89-40f7-b276-094997d6ff70)
The logo in footer dissapears on light theme

2024-03-06 21:33 UTC, valery-chumak commented on frontend/src/bundles/landing/pages/landing.tsx
> +                            <img src={logo} alt="Logo" />
Here too
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/fe834b69-e274-451a-9052-61880f373895)

2024-03-06 21:35 UTC, valery-chumak commented on frontend/src/bundles/landing/pages/landing.tsx
> +                            <img src={logo} alt="Logo" />
It looks really great, especially the animation) Cool work)

2024-03-07 09:51 UTC, stpalamar commented on frontend/src/bundles/landing/pages/landing.tsx
> +                            <img src={logo} alt="Logo" />
Thanks! I will fix logo

2024-03-07 10:08 UTC, stpalamar commented
Fixed the logo, I took implementation from #265 
![2024-03-07_12-04](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/46ad9132-9ee7-4be3-875d-97e1827c0884)
![2024-03-07_12-04_1](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/a06e9c7b-f5f2-4305-b3b5-0a19787bb16b)
![2024-03-07_12-04_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/cd679b0c-14df-4221-a216-09f2d9ed5f93)
![2024-03-07_12-04_3](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/9fa49213-c327-4bde-a93c-8e0b38ab8172)

2024-03-07 10:17 UTC, valery-chumak submitted a review, later dismissed

2024-03-07 11:04 UTC, stpalamar commented
Changed the name of the buttons
![2024-03-07_13-03](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/6e70e0cc-2e93-4d7e-8c5d-71a0edb61bc6)
![2024-03-07_13-04](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/9576ec15-ad24-4370-8bf3-0764a055cf06)
![2024-03-07_13-04_1](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/d570e1db-e43f-426b-b493-00ae574c5060)
![2024-03-07_13-04_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/a1689965-cf42-420b-87db-a3da165c204c)

2024-03-07 11:55 UTC, nikita-remeslov approved these changes

2024-03-07 11:55 UTC, merged