LIME-266:  Connect OAuth to client
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #313
Opened 2024-03-06 14:14 UTC by SofiiaTrokhymchuk

Can't test the authorize/deauthorize button click flow because of CORS error
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/414e23d7-1931-418e-8e67-668ea91c18d5)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/a0e641f4-ce47-4ca4-9582-ee905a5d6357)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/825b3635-2a54-444a-8fba-9ca91911a480)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/30eebccd-7aed-4279-8e3a-a260a77e5399)

2024-03-06 14:29 UTC, anton-otroshchenko commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105710998/80292325-e767-4dc6-a4a7-01a8527912ec)
Try to initialize cors before other plugins because sometimes they may break it

2024-03-06 14:33 UTC, SofiiaTrokhymchuk commented
Also doesn't work : (

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/afd27aef-7287-44b9-9bc4-675dac020ce0)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/4455ffb1-571e-4329-9e92-b27c63f6d29c)

2024-03-06 14:35 UTC, anton-otroshchenko commented
Did you try to specify the origin url for strava?

2024-03-06 14:36 UTC, SofiiaTrokhymchuk commented
If I specify origin and methods explicitly this also doesn't work
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/6f1f77fe-c39d-4856-a03d-72d6fe4b691c)

2024-03-06 14:38 UTC, anton-otroshchenko commented
But you recieve your request not from our client but directly from strava or no?

2024-03-06 14:41 UTC, SofiiaTrokhymchuk commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/b93782ef-7c4e-438a-9c0e-245769ba2041)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/211ed76b-8412-4d40-a77e-da0906043916)

2024-03-06 14:45 UTC, anton-otroshchenko commented
fastify.register(cors, { origin: '*', credentials: true, }) 
try this

2024-03-06 14:48 UTC, anton-otroshchenko commented
also check this please maybe it will help
https://groups.google.com/g/strava-api/c/YizXJN5EBM4
https://stackoverflow.com/questions/56461110/oauth2-httprequest-cors-policy

2024-03-07 15:55 UTC, SofiiaTrokhymchuk commented
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/93663923/899b2a12-3618-4b08-abf3-bfc3633c80c6

2024-03-07 18:10 UTC, dimapopovych requested changes
small changes required, probably could be merged after resolution
lgtm

2024-03-07 18:10 UTC, dimapopovych commented on frontend/src/bundles/profile/pages/connections-page/connections-api.ts
> +        const fullPath = `${this.connectionsPath}${ConnectionsPath.ROOT}`;
just pass parts to getFullEndpoint

2024-03-07 18:10 UTC, dimapopovych commented on frontend/src/bundles/profile/pages/connections-page/connections-api.ts
> +        });
```suggestion
        const response = await this.load(this.getFullEndpoint(this.oAuthPath, OAuthActionsPath.$PROVIDER_AUTORIZE, { provider }), {
            method: 'GET',
            contentType: ContentType.JSON,
            hasAuth: true,
        });
```

2024-03-07 18:10 UTC, dimapopovych commented on frontend/src/bundles/profile/pages/connections-page/components/connection-option.tsx
> +        setIsConnected(!!providerIsConnected);
```suggestion
        const existingConnection = connections.find(
            (connection) => connection.provider === provider,
        );

        setIsConnected(Boolean(existingConnection));
```

2024-03-07 22:57 UTC, SofiiaTrokhymchuk commented
I have also updated a little bit the `deauthorize` method to refresh the token if needed before the deauthorization, because I've found the bug that user can't deauthorize if token is expired and is not refreshed. Now everything works perfectly fine

2024-03-08 08:13 UTC, nikita-remeslov submitted a review, later dismissed

2024-03-08 08:14 UTC, dimapopovych approved these changes, later dismissed

2024-03-08 08:44 UTC, dimapopovych approved these changes

2024-03-08 08:49 UTC, merged