LIME-259: * Rewritting selectors to fix warnings
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #355
Opened 2024-03-08 16:16 UTC by DavidCharif

Local navigation through routes without warnings
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/53844f42-f71e-4a4b-9329-6815b5c9562a)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/7666955e-1f21-48b3-8fbc-f8064cf86808)

2024-03-11 08:35 UTC, dimapopovych requested changes

2024-03-11 08:35 UTC, dimapopovych commented on frontend/src/bundles/auth/pages/auth.tsx
> +    const user = useAppSelector(({ auth }) => auth.user);
you don't need to create separate selectors to get data from one slice, could select whole slice and use destructuring

2024-03-11 09:55 UTC, nikita-remeslov requested changes

2024-03-11 09:55 UTC, nikita-remeslov commented on frontend/src/bundles/auth/pages/auth.tsx
> +    const user = useAppSelector(({ auth }) => auth.user);
```suggestion
    const { dataStatus, user } = useAppSelector(({ auth }) => auth);
```

2024-03-11 10:25 UTC, DavidCharif commented on frontend/src/bundles/auth/pages/auth.tsx
> +    const user = useAppSelector(({ auth }) => auth.user);
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/e2cf12e0-bf32-4c27-a8b1-d3579308ba6e)

2024-03-11 21:29 UTC, dimapopovych requested changes

2024-03-11 21:29 UTC, dimapopovych commented on frontend/src/bundles/common/components/protected-route/protected-route.tsx
> +    const { isRefreshing, user: userAuthenticated } = useAppSelector(
I don't think that renaming here is necessary

2024-03-11 21:29 UTC, dimapopovych commented on frontend/src/bundles/goals/pages/goals.tsx
> +    const goals = useAppSelector(({ goals }) => goals.goals);
multiple selectors is unnecessary

2024-03-11 21:29 UTC, dimapopovych commented on frontend/src/bundles/goals/pages/goals.tsx
> +        ({ achievements }) => achievements.achievements,
multiple selectors is unnecessary

2024-03-12 10:10 UTC, nikita-remeslov commented
Conflicts

2024-03-12 22:05 UTC, stpalamar submitted a review, later dismissed

2024-03-13 21:12 UTC, dimapopovych submitted a review, later dismissed

2024-03-14 17:19 UTC, ArtemLymarenko approved these changes, later dismissed

2024-03-14 17:36 UTC, valery-chumak requested changes

2024-03-14 17:36 UTC, valery-chumak commented on frontend/src/bundles/common/components/theme-switcher/theme-switcher.tsx
> +    const theme = useAppSelector(({ theme }) => theme.theme);
const { theme } = useAppSelector(({ theme }) => theme);

2024-03-14 17:36 UTC, valery-chumak commented on frontend/src/bundles/landing/pages/landing.tsx
> +    const theme = useAppSelector(({ theme }) => theme.theme);
const { theme } = useAppSelector(({ theme }) => theme);

2024-03-14 17:36 UTC, valery-chumak commented on frontend/src/bundles/profile/pages/connections-page/components/connection-option.tsx
> +    const connections = useAppSelector(
const { connections } = useAppSelector(({ connections }) => connections);

2024-03-14 17:36 UTC, valery-chumak commented on frontend/src/bundles/workouts/pages/workout-item/workout-items.tsx
> +    const workouts = useAppSelector(({ workouts }) => workouts.workouts);
const { workouts } = useAppSelector(({ workouts }) => workouts );

2024-03-14 17:36 UTC, valery-chumak commented on frontend/src/bundles/subscription/pages/subscription-checkout/subscription-checkout.tsx
> +    const theme = useAppSelector(({ theme }) => theme.theme);
const { theme } = useAppSelector(({ theme }) => theme);

2024-03-14 17:37 UTC, stpalamar commented on frontend/src/bundles/workouts/pages/workout-item/workout-items.tsx
> +    const workouts = useAppSelector(({ workouts }) => workouts.workouts);
```suggestion
    const { workouts } = useAppSelector(({ workouts }) => workouts);
```

2024-03-14 17:38 UTC, stpalamar commented on frontend/src/bundles/workouts/pages/workout-item/workout-items.tsx
> +    const workouts = useAppSelector(({ workouts }) => workouts.workouts);
no a big deal but it better follow the same code style)

2024-03-14 17:41 UTC, stpalamar commented on frontend/src/bundles/workouts/pages/workout-item/workout-items.tsx
> +    const workouts = useAppSelector(({ workouts }) => workouts.workouts);
like Valeriia already mentioned above)

2024-03-14 18:05 UTC, valery-chumak approved these changes

2024-03-14 18:30 UTC, ArtemLymarenko approved these changes

2024-03-14 20:46 UTC, nikita-remeslov approved these changes

2024-03-14 20:46 UTC, merged