LIME-154:  Leaving page with saving changes
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #360
Opened 2024-03-10 00:20 UTC by VasylynaKolodiy

There are certain problems in this PR that I have not been able to solve. Maybe I didn't choose the best way to solve this issue.

**1)** I removed StrictMode in index.tsx. Because with it a modal window appears even if no changes are made. (I am attaching the video below).

**2)** For example, we want to leave the information page and go to connections. We made certain changes on the information page that we did not save. Accordingly, we have a modal window that offers us to save the changes. We click Save, the changes are saved, but we continue to stay on the information page.

**3)** When we click Reset and don't save the changes, the modal window doesn't appear (because Reset changes the value of isDirty to false)

**P.S.** It seems to me that the Reset button is not working correctly now. It would probably be better not to clear the data completely, but to return the last saved data.

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/106997950/e59c5809-1dc6-43b9-b4d6-b5f6eefdca5e

2024-03-11 22:30 UTC, stpalamar commented
I guess removing StrictMode is not the solution because it is needed for the development process and it's not used in production build.
I made `shouldUnregister: true` and a modal doesn't appear when the user did not change a form. You can try it and double-check if it doesn't broke form logic

Or maybe don't use `isDirty`. For example, You can compare form inputs with user in the redux store

2024-03-12 09:07 UTC, VasylynaKolodiy commented
> I guess removing StrictMode is not the solution because it is needed for the development process and it's not used in production build. I made `shouldUnregister: true` and a modal doesn't appear when the user did not change a form. You can try it and double-check if it doesn't broke form logic
> 
> Or maybe don't use `isDirty`. For example, You can compare form inputs with user in the redux store

@stpalamar Thank you very much for the advice. I will try.

2024-03-18 23:21 UTC, stpalamar commented on package-lock.json
looks good, but why there are changes in package-lock.json?

2024-03-19 08:56 UTC, VasylynaKolodiy commented on package-lock.json
@stpalamar thank you)
I did not notice that.
Maybe it happened because I created this branch more than a week ago and the old file is dragging behind me.
So I updated the latest changes from development and modified the package-lock.json relative to them.

2024-03-19 13:33 UTC, stpalamar approved these changes, later dismissed

2024-03-20 18:56 UTC, SergiiTernytskyi approved these changes, later dismissed

2024-03-20 19:39 UTC, valery-chumak approved these changes, later dismissed

2024-03-21 20:49 UTC, nikita-remeslov requested changes

2024-03-21 20:49 UTC, nikita-remeslov commented on package.json
we dont need to change this file

2024-03-21 21:29 UTC, nikita-remeslov approved these changes

2024-03-21 21:29 UTC, merged