LIME-372: Center goals page
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #376
Opened 2024-03-11 15:42 UTC by DavidCharif

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/b1f43f4c-cc03-4676-ba31-4189ff786c70)

2024-03-11 22:07 UTC, valery-chumak requested changes

2024-03-11 22:07 UTC, valery-chumak commented on frontend/src/bundles/goals/pages/goals.tsx
> +        <main className="bg-secondary ml-auto mr-auto flex w-full max-w-[1136px] flex-col gap-8 md:justify-between lg:flex-row lg:justify-normal xl:flex xl:gap-8">
You can use `mx-auto`

2024-03-11 22:07 UTC, valery-chumak commented on frontend/src/bundles/goals/pages/goals.tsx
> +        <main className="bg-secondary ml-auto mr-auto flex w-full max-w-[1136px] flex-col gap-8 md:justify-between lg:flex-row lg:justify-normal xl:flex xl:gap-8">
We should use rem instead of px

2024-03-12 22:28 UTC, closed without merging

2024-03-12 22:28 UTC, DavidCharif commented
Already solved on https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/379