LIME-369: Goal banner is displayed without content on Goals page when screen width is 767 and less and if no goals are in progress
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #377
Opened 2024-03-11 16:39 UTC by SergiiTernytskyi

https://www.loom.com/share/fef16d3571eb493c92f4a2f74d0353f7

2024-03-12 10:23 UTC, nikita-remeslov commented
Content should be centered, check Overview page

2024-03-12 10:36 UTC, SergiiTernytskyi commented
> Content should be centered see Overview page

I know, but It is ticket https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/372, so I did not fixed it.

2024-03-12 10:41 UTC, SergiiTernytskyi commented
> Content should be centered, check Overview page

For this purpose we have https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/issues/372. Or should I change here?

2024-03-12 22:44 UTC, dimapopovych requested changes

2024-03-12 22:44 UTC, dimapopovych commented on frontend/src/bundles/overview/components/goal-widget/goal-widget.tsx
> +                    className={`font-heavybold text-lm-black-200 text-xl leading-7 md:text-[1.5rem]  ${hasAchievement ? 'hidden md:block' : ''}`}
let's use getValidClassNames helper for combining styles

2024-03-14 17:47 UTC, valery-chumak approved these changes

2024-03-14 18:37 UTC, jhladkov approved these changes

2024-03-14 18:37 UTC, ArtemLymarenko approved these changes

2024-03-14 20:45 UTC, nikita-remeslov approved these changes

2024-03-14 20:45 UTC, merged