LIME-311: Added endpoints to get data from google fit
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #387
Opened 2024-03-11 23:23 UTC by jhladkov

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/74872088/c54e078d-bb8e-4288-8270-358766ebc9a6

2024-03-13 22:04 UTC, dimapopovych requested changes

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/google-fit.service.ts
> +            : accessToken;
why do you need checkAccessToken? 
I think that getAccessToken already does that and gets new token pair if token is expired

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/google-fit.service.ts
> +        ).toISOString();
```suggestion
       const startTime = new Date();
       startTime.setMonth(startTime.getMonth()-1)
```

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/google-fit.service.ts
> +    }
I think there should be no issues if we will handle it in parallel, not sequentially. What do you think?

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/helpers/format-google-fit-response.helper.ts
> +};
do we really need this switch? 
I think simple map object google fit activity -> our activity will be enough

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/helpers/format-google-fit-response.helper.ts
> +};
Also I all except this function in this file is not helpers and should be moved to service

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/google-fit.service.ts
> +        });
I think you should get here only google fit workouts. Since looks like this will delete all the workouts from from Strava. Or am I missing something?

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/google-fit/helpers/prepare-actions.helper.ts
> +const prepareActions = (
I think we could just get two sets of activity ids from DB and from response and find 
- Differences for create / delete
- Intersection for updates
Then map results into actions, should be a lot more efficient

2024-03-13 22:04 UTC, dimapopovych commented on backend/src/bundles/users/user.controller.ts
> +            await googleFitService.handleData(oAuthEntity);
I think we could just skip await here and return a response

2024-03-14 07:57 UTC, nikita-remeslov commented on backend/src/bundles/google-fit/google-fit.service.ts
> +    }
I think it should be in parallel

2024-03-14 15:43 UTC, dimapopovych submitted a review, later dismissed

2024-03-14 20:37 UTC, nikita-remeslov approved these changes, later dismissed

2024-03-14 21:11 UTC, valery-chumak submitted a review, later dismissed

2024-03-14 21:52 UTC, merged