LIME-37:  Add breakpoints
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #40
Opened 2024-02-12 16:03 UTC by SergiiTernytskyi

Added default breakpoints

2024-02-12 16:35 UTC, DavidCharif reviewed
Maybe add also add a phone/mobile breakpoint, but about this I'm not sure.

2024-02-12 19:00 UTC, DavidCharif approved these changes

2024-02-12 20:14 UTC, nikita-remeslov requested changes
Let override the default tailwind value

2024-02-12 21:58 UTC, dimapopovych approved these changes

2024-02-13 08:27 UTC, jhladkov approved these changes

2024-02-13 09:58 UTC, stpalamar approved these changes

2024-02-13 10:27 UTC, nikita-remeslov approved these changes

2024-02-13 10:27 UTC, merged