LIME-198: Add automatic calculation for goals and achievements
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #417
Opened 2024-03-13 19:19 UTC by SergiiTernytskyi

Add automatic calculation for goals and achievements

2024-03-13 19:54 UTC, SergiiTernytskyi commented
https://www.loom.com/share/6bbe3a19930749c083d594f7aeb4fcd7

2024-03-14 18:24 UTC, jhladkov commented on backend/src/common/helpers/check-walking-achievement-helper.ts
> +                    .length > ZERO_VALUE
Try to avoid magic numbers

2024-03-14 18:32 UTC, jhladkov commented on backend/src/common/services/calculation-progress/calculation-progress.service.ts
> +        }
You can simplify it like this:  
`userAchievements.push(...uniqueCyclingAchievements);`
Spreading an empty array into another array has no effect, so the condition is not necessary.

2024-03-14 18:32 UTC, jhladkov commented on backend/src/common/services/calculation-progress/calculation-progress.service.ts
> +        }
same here

2024-03-14 18:33 UTC, jhladkov commented on backend/src/common/services/calculation-progress/calculation-progress.service.ts
> +        }
and here

2024-03-19 13:38 UTC, nikita-remeslov requested changes

2024-03-19 13:38 UTC, nikita-remeslov commented on backend/src/bundles/achievements/achievement.controller.ts
> +     * /api/v1/achievements/current-user:
we have an endpoint for finding everything by user id
`/api/v1/achievements/user/{id}`

2024-03-19 14:23 UTC, nikita-remeslov requested changes
if I add new achievement your code will not work,

we need to get all achievements/goals related to workout type, get the first one and calculate it. We can not check everything separately

2024-03-19 14:23 UTC, nikita-remeslov commented on shared/src/bundles/achievements/enums/achievements-api-path.enum.ts
> +    CURRENT_USER: '/current-user-achievements',
we dont have such path

2024-03-19 14:55 UTC, dimapopovych commented
@SergiiTernytskyi 
Here's the proposed approach for achievements
When a new workout is created, we collect all uncompleted achievements that have an activityType matching the newly created workout, along with all previous workouts for this activityType. Subsequently, we calculate the total distance, kilocalories, duration, and steps for the workouts. Next, we filter the selected achievements by verifying if the achievement meets the requirements based on the requirementMetric. We should map the requirementMetric to the previously calculated total and compare it to the requirement. If this comparison is successful, the achievement is considered completed.
I think this should work, but double-check for unexpected pitfalls.

2024-03-19 15:08 UTC, dimapopovych commented
For goals, you need to calculate the number of workouts that meet the specified conditions within a certain period. 
For example, if the goal is to run 3 times per week for 10 km each with a duration of 50 minutes, you could run 100 times in a week. However, if only two of these workouts have distance > 10 km with a duration exceeding 50 minutes, you would achieve a completion rate of 2 out of 3 for the goal.

2024-03-19 15:08 UTC, dimapopovych commented
Please share your thoughts about this

2024-03-19 15:10 UTC, SergiiTernytskyi commented
> For goals, you need to calculate the number of workouts that meet the specified conditions within a certain period. For example, if the goal is to run 3 times per week for 10 km each with a duration of 50 minutes, you could run 100 times in a week. However, if only two of these workouts have distance > 10 km with a duration exceeding 50 minutes, you would achieve a completion rate of 2 out of 3 for the goal.


So we have distance per one workout

2024-03-19 21:31 UTC, dimapopovych requested changes

2024-03-19 21:31 UTC, dimapopovych commented on backend/src/common/services/calculation-progress/calculation-progress.service.ts
> +    }
let's just pass userId and activityType to this function then get workouts by this activity type and pass workouts as arguments to updateGoalsProgress/updateAchieventsProgress (rename pls) as we don't want to select same data twice.

2024-03-19 21:31 UTC, dimapopovych commented on backend/src/common/services/calculation-progress/calculation-progress.service.ts
> +        });
you don't need to get all workouts, could already get pre-filtered for specific activity type, the same applies to goals/achievements etc.

2024-03-19 21:31 UTC, dimapopovych commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +            progress = calculateProgress(goal, todayWorkouts);
Why is the calculateProgress function needed? 
I believe we can achieve this by filtering workouts based on set criteria. We can filter workouts by date, by distance (if specified in goal), and by duration (if specified in goal). Then, we can compare the number of workouts to the goal frequency to calculate the progress towards the goal.
Or am I missing something?

2024-03-20 08:45 UTC, dimapopovych requested changes

2024-03-20 08:45 UTC, dimapopovych commented on backend/src/common/services/calculation-progress/calculation-progress.service.ts
> +                calculateGoalProgress(goal, workouts) ===
i don't think that we need to call this fn three times)

2024-03-20 08:45 UTC, dimapopovych commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +            );
Currently, it doesn't take into account duration because the distance comparison returns a boolean. I would like to do it more readable and correct.

2024-03-20 08:45 UTC, dimapopovych commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +            );
Also I'm curious why do you need so many `as` operators? Not only here, but throughout entire PR.

2024-03-20 13:45 UTC, dimapopovych requested changes

2024-03-20 13:45 UTC, dimapopovych commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +    }
we could enter only distance OR duration? Because if not, we should check both conditions.

2024-03-20 13:45 UTC, dimapopovych commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +        case FrequencyType.WEEK: {
I think we also have month frequency. Or am I mistaken?

2024-03-20 13:55 UTC, SergiiTernytskyi commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +    }
For now we can choose what to enter

2024-03-20 13:56 UTC, SergiiTernytskyi commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +    }
Or you think if we have both, we need to add condition?

2024-03-20 13:58 UTC, SergiiTernytskyi commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +        case FrequencyType.WEEK: {
Yes, in general we have month, but add it in modal for goal is impossible, there is only day and a week. Do I need to add month frequency processing?

2024-03-20 14:56 UTC, SergiiTernytskyi commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +        case FrequencyType.WEEK: {
we even don't have achievements for month frequency

2024-03-20 17:46 UTC, dimapopovych submitted a review, later dismissed
But fix comment please

2024-03-20 17:46 UTC, dimapopovych commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +const checkGoal = (
```suggestion
const checkGoal = (
    workout: WorkoutResponseDto,
    goal: GoalResponseDto,
): boolean => {
	let isMatched = true;
	if (goal.distance) {
		isMatched = workout.distance >= goal.distance;
	}
	if (isMatched && goal.duration) {
		isMatched = convertSecondToMinutes(workout.duration) >= goal.duration;
	}
    return isMatched;
};
```

2024-03-20 18:08 UTC, SergiiTernytskyi commented on backend/src/common/helpers/calculate-goal-progress-helper.ts
> +const checkGoal = (
Done

2024-03-20 20:17 UTC, dimapopovych approved these changes

2024-03-21 09:30 UTC, nikita-remeslov approved these changes

2024-03-21 09:30 UTC, merged