LIME-354: + add advertisement banners to pages
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #422
Opened 2024-03-14 19:49 UTC by ivanbilobrov07

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/c17c53e6-b79f-4824-9d8c-b67fdb3ece12)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/a15c6120-f9eb-432c-ad02-6bdbd6d31142)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/4765b6ee-2fdb-4ead-a6fe-f0779f2e313c)

2024-03-14 20:36 UTC, nikita-remeslov commented
@ivanbilobrov07 Could you add mobile view screens?

2024-03-14 20:40 UTC, ivanbilobrov07 commented
At the moment, there is 1 in the home page and 1 in the goals

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/2d03d7c7-9c29-4076-9770-354f3ca91526)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/f0403f38-c1c4-47cc-9ab7-a1e7ff9afc3e)

2024-03-14 20:41 UTC, ivanbilobrov07 commented
Also, I just noticed that they have different height, so I will fix it now

2024-03-14 21:01 UTC, jhladkov commented on frontend/src/bundles/goals/pages/goals.tsx
> +                                        (lastGoal?.duration as number)
You can write it once and store in variable. 
`const YOUR_VARIABLE_NAME= (lastGoal?.distance as number) || (lastGoal?.duration as number);`

```
value={YOUR_VARIABLE_NAME}
target={YOUR_VARIABLE_NAME}
```

2024-03-14 21:02 UTC, dimapopovych submitted a review, later dismissed

2024-03-15 15:30 UTC, stpalamar requested changes

2024-03-15 15:30 UTC, stpalamar commented on frontend/src/bundles/common/components/google-ads/google-ads.tsx
>  type GoogleAdsProperties = {
```suggestion
type Properties = {
```

2024-03-15 19:10 UTC, SofiiaTrokhymchuk requested changes

2024-03-15 19:10 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/common/components/base-layout/base-layout.tsx
>  import { getValidClassNames } from '../../helpers/helpers.js';
Please, use proper imports

2024-03-15 19:10 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/common/components/base-layout/base-layout.tsx
> +import { useAppSelector, useSidebarToggle } from '../../hooks/hooks.js';
imports

2024-03-15 19:10 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/common/components/modal/modal.tsx
> +        overlayClass: `overlay bg-overlay fixed inset-0 z-50 ${isOpen ? 'opacity-1' : 'opacity-0 pointer-events-none'}`,
use getValidClassNames

2024-03-18 15:35 UTC, nikita-remeslov approved these changes

2024-03-18 15:35 UTC, merged