LIME-430: Add unique profile preferences
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #440
Opened 2024-03-15 14:41 UTC by valery-chumak

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/a999d1f6-03b0-4a0c-ae56-baa8348de51d

2024-03-15 15:48 UTC, stpalamar commented on frontend/src/bundles/profile/components/personal-details/personal-details.tsx
> +                        getUniqueValues(goals, 'activityType').map((goal) => (
maybe save 'activityType' key as constant?

2024-03-15 16:22 UTC, valery-chumak commented on frontend/src/bundles/profile/components/personal-details/personal-details.tsx
> +                        getUniqueValues(goals, 'activityType').map((goal) => (
Fixed)

2024-03-15 16:32 UTC, jhladkov approved these changes, later dismissed

2024-03-15 16:41 UTC, DavidCharif approved these changes, later dismissed

2024-03-15 19:11 UTC, SofiiaTrokhymchuk requested changes

2024-03-15 19:11 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/profile/components/personal-details/personal-details.tsx
> +                    className={`${isFollowed ? 'text-action hover:border-buttonSecondary hover:text-buttonSecondary' : 'text-lm-grey-200'} inline-flex min-h-12 min-w-12 items-center justify-center ro
use getValidClassNames

2024-03-15 20:35 UTC, valery-chumak commented on frontend/src/bundles/profile/components/personal-details/personal-details.tsx
> +                    className={`${isFollowed ? 'text-action hover:border-buttonSecondary hover:text-buttonSecondary' : 'text-lm-grey-200'} inline-flex min-h-12 min-w-12 items-center justify-center ro
Fixed)

2024-03-16 00:40 UTC, nikita-remeslov approved these changes

2024-03-16 00:40 UTC, merged