LIME-450: Constrains to upload image file type.
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #451
Opened 2024-03-18 14:03 UTC by DavidCharif

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/57aa5a5a-7c58-4be7-9512-24732f71fb0c)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/7112e41c-c2af-4d25-a2aa-b6a954c8076f

2024-03-18 21:39 UTC, dimapopovych requested changes

2024-03-18 21:39 UTC, dimapopovych commented on frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx
> +    const [imgFileError, setImgFileError] = useState(false);
let's just show toast notification

2024-03-19 11:20 UTC, stpalamar approved these changes

2024-03-19 20:48 UTC, dimapopovych approved these changes

2024-03-20 10:29 UTC, merged