LIME-437: Add and delete workouts manually
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #455
Opened 2024-03-18 19:42 UTC by stpalamar

**The delete button is available only for workouts without a provider**
**km and km/h converts to meters and m/s**

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/3a1d4ca3-3329-4c36-a2de-5ec77a2e27ad

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/95b94835-307c-4df1-ac37-a5aa35cbfa21

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/09bdb131-8eea-4d88-bb92-5e2c37ad3771

2024-03-18 21:33 UTC, dimapopovych requested changes

2024-03-18 21:33 UTC, dimapopovych commented on frontend/src/bundles/workouts/components/create-workout-form/constants/constants.ts
> +    provider: null,
Why do we need provider here?

2024-03-18 21:33 UTC, dimapopovych commented on frontend/src/bundles/workouts/components/create-workout-form/constants/constants.ts
> +const WORKOUT_ACTIVITY_OPTIONS = [
I think we already have similar selector with ActivityType somewhere, maybe we could reuse options?

2024-03-18 21:33 UTC, dimapopovych commented on shared/src/helpers/configure-date/configure-date.ts
> +const configureDate = (
We don't have similar helper? And as I can see you are not using it on backend, so maybe worth to move it to frontend and utilize date-fns to simplify

2024-03-18 21:33 UTC, dimapopovych commented on shared/src/helpers/configure-time-string/configure-time-string.ts
> +function configureTimeString(isoString: string | null): string {
same question for this one

2024-03-20 21:10 UTC, dimapopovych submitted a review, later dismissed

2024-03-20 22:04 UTC, SergiiTernytskyi approved these changes, later dismissed

2024-03-21 21:15 UTC, stpalamar commented
Adapted for new sub-navigation

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/26843161/f2021d1e-fb65-4df2-9cec-e7a3fae3a75b

2024-03-21 21:16 UTC, nikita-remeslov approved these changes

2024-03-21 21:16 UTC, merged