LIME-463: BUG: Workout card for walking activity displays 0 km when distance > 0, steps = 0, provider null
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #464
Opened 2024-03-19 11:22 UTC by DavidCharif

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/a1edd7c5-d810-4c38-9660-414e7635e86c)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/5d872d41-a1c7-43e3-9eb9-80e412f95cab)

2024-03-19 16:57 UTC, stpalamar submitted a review, later dismissed

2024-03-20 07:32 UTC, anton-otroshchenko requested changes

2024-03-20 07:32 UTC, anton-otroshchenko commented on frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx
> +        steps && steps != 0 ? steps : metersToKilometers(distance);
```suggestion
        steps && steps !== 0 ? steps : metersToKilometers(distance);
```

2024-03-20 19:58 UTC, stpalamar approved these changes

2024-03-20 21:08 UTC, dimapopovych commented on frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx
> +        steps && steps !== 0 ? steps : metersToKilometers(distance);
const workoutDistance = steps || metersToKilometers(distance);

just curious, is this disallowed by linter? no need to adjust

2024-03-21 01:30 UTC, DavidCharif commented on frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx
> +        steps && steps !== 0 ? steps : metersToKilometers(distance);
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/e5f18b84-6639-4136-ac6a-5dfa218b1af3)
No, it is valid i just went to the direct approach without seeing that option

2024-03-21 09:37 UTC, nikita-remeslov approved these changes

2024-03-21 09:37 UTC, merged