LIME-8: Add toggle component
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #48
Opened 2024-02-13 12:18 UTC by SergiiTernytskyi

Create a reusable Toggle component that integrates with react-hook-form

2024-02-13 12:21 UTC, nikita-remeslov requested changes

2024-02-13 12:21 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/toggle/toggle.tsx
you should add an error state. see input component

2024-02-13 14:45 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/common/components/toggle/toggle.tsx
> +};
It is better to use map structure for classes as in [21 PR](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/pull/21) to keep the code consistency throughout the project

2024-02-13 16:12 UTC, SergiiTernytskyi commented on frontend/src/bundles/common/components/toggle/toggle.tsx
> +};
Thanks for Your suggestion Its can't be a map structure, because all classes are needed for one component always. Here we do not have a choice according to props. Classes were made to make it easier to read tailwind classes. It can be written in one string.

2024-02-13 19:40 UTC, SergiiTernytskyi commented
![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/105019200/4420facb-ec4b-404c-99c4-c2d33bcd047f)

2024-02-14 07:49 UTC, anton-otroshchenko commented on frontend/src/bundles/common/components/toggle/toggle.tsx
> +            >
I think you should use getValidClassNames helper here since you've already used in this file for large classNames

2024-02-14 10:24 UTC, nikita-remeslov approved these changes

2024-02-14 10:27 UTC, SofiiaTrokhymchuk approved these changes

2024-02-14 10:29 UTC, merged