LIME-536: Fix extra achievements
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #538
Opened 2024-03-21 18:12 UTC by SergiiTernytskyi

2024-03-21 20:43 UTC, nikita-remeslov requested changes
why we change it? why we dont have half marathon?

2024-03-21 20:50 UTC, dimapopovych commented
@nikita-remeslov 
we are not storing time restrictions in database at all. These are only in achievements names. Need to change database structure/seeds/calculation logic to handle it.

2024-03-21 20:54 UTC, SergiiTernytskyi commented
> why we change it? why we dont have half marathon?

We have half marathon. There just was 21 km - half marathon and 42 km- half marathon

2024-03-21 21:17 UTC, dimapopovych commented
@SergiiTernytskyi 
Could you please remove all achievements with time restrictions and replace them with total [stat] achievements? This change is necessary to avoid confusion, as there are still a couple with incorrect names based on how they will be calculated.
```
{
        name: 'First 1 hour run',
        activityType: ActivityType.RUNNING,
        requirement: 60,
        requirementMetric: Metric.MINUTES,
    },
    {
        name: '100 km in a month',
        activityType: ActivityType.RUNNING,
        requirement: 100,
        requirementMetric: Metric.KILOMETERS,
    },
    {
        name: '200 km in a month',
        activityType: ActivityType.RUNNING,
        requirement: 200,
        requirementMetric: Metric.KILOMETERS,
    },
```

Like these, for example

2024-03-21 22:06 UTC, dimapopovych approved these changes, later dismissed

2024-03-21 22:06 UTC, dimapopovych commented on backend/src/seeds/achievements.ts
> +        name: 'Running Milestone: 42 km (marathon)',
remove half marathon/marathon

2024-03-21 22:06 UTC, dimapopovych commented on backend/src/seeds/achievements.ts
> +        name: 'Calories Milestone: 1000 kcal burned',
Walking Milestone: 100 kcal burned

2024-03-22 08:00 UTC, anton-otroshchenko approved these changes

2024-03-22 08:24 UTC, dimapopovych approved these changes

2024-03-22 09:58 UTC, merged