LIME-47: + create-modal-component
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #71
Opened 2024-02-14 23:28 UTC by velisssa

Created a common component Modal in which we can pass elements.

A screenshot of the modal window:

![screenshot-modal](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/106997950/4daef05d-1b14-42ed-b6eb-890ef33c6df2)

2024-02-15 15:20 UTC, nikita-remeslov requested changes

2024-02-15 15:20 UTC, nikita-remeslov commented on frontend/src/assets/img/close.svg
we can use some icon from tailwind - https://heroicons.com/

2024-02-15 21:46 UTC, nikita-remeslov approved these changes

2024-02-15 21:46 UTC, velisssa commented on frontend/src/assets/img/close.svg
thanks, fixed it

2024-02-15 21:46 UTC, velisssa commented on frontend/src/assets/img/close.svg
thanks, I fixed it

2024-02-16 07:25 UTC, anton-otroshchenko approved these changes

2024-02-16 09:01 UTC, merged