LIME-82: Add Connections page
BinaryStudioAcademy/bsa-winter-2023-2024-lime pull request #94
Opened 2024-02-16 17:02 UTC by Fun1engine

Added connections page.

Result.

![connection-0](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/9f1416cb-3254-46c5-a846-ed46027d19e1)
![connection-1](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/b5e6d02d-79f6-4ee5-9fba-61d6e5e67506)
![connection-2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/ec15030c-cf2d-48c6-b6c6-c8f16645fe9c)
![connection-3](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/17fb8844-3099-476a-8991-2bf1125b4fad)

2024-02-16 20:17 UTC, SofiiaTrokhymchuk commented on frontend/src/bundles/profile/pages/connections-page/components/connection-option.tsx
> +                            'h-6 max-w-[180px] sm:h-10 sm:max-w-40 md:max-w-60'
it's better to use rem not px

2024-02-16 21:30 UTC, JKaypa commented on frontend/src/bundles/profile/pages/connections-page/components/connection-option.tsx
> +    const handleClick = useCallback((): undefined => {
Instead of undefined, I think you can better place void

2024-02-19 14:52 UTC, nikita-remeslov commented
Do you use this red color?
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/73cf7f19-e98a-4888-8df3-fa3c8a3d339e)

2024-02-19 14:54 UTC, nikita-remeslov requested changes
Lets center icon and button for mobile view
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/78347072/84b14e7e-70d2-4d12-9ac6-0ccca46aeb74)

2024-02-19 14:57 UTC, nikita-remeslov requested changes

2024-02-19 14:57 UTC, nikita-remeslov commented on frontend/src/bundles/profile/pages/connections-page/components/styles.module.css
> +@media (width >= 600px) {
we should use our screen sizes. check tailwind config

2024-02-19 14:57 UTC, nikita-remeslov commented on frontend/src/bundles/profile/pages/connections-page/components/styles.module.css
> +@media (width >= 600px) {
also you can add classes like `lg:flex md:block....`

2024-02-19 15:30 UTC, Fun1engine commented
Updated layout

![11](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/5cabf687-5d94-40de-852e-148c64169722)
![12](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/7ed31181-7e91-4ac4-badb-cab3cf31c62e)
![13](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/c74f3d77-57a2-4497-ac3b-5c344f7d94fa)
![14](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/92994963/a5e6d402-c32d-41c6-b63f-24d68fd29440)

2024-02-19 19:24 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/icon/types/icon.type.ts
> +type IconName =
lets create enum for it

2024-02-20 18:58 UTC, dimapopovych approved these changes

2024-02-21 14:42 UTC, DavidCharif approved these changes

2024-02-22 19:10 UTC, valery-chumak approved these changes

2024-02-22 19:11 UTC, stpalamar approved these changes

2024-02-23 11:01 UTC, nikita-remeslov approved these changes

2024-02-23 11:01 UTC, merged